erp/urls.py
from django.conf.urls import patterns, include, url
import os.path
from erp.settings import STATIC_URL, MEDIA_ROOT
from django.views.generic.simple import redirect_to
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# For DajaxIce to work
from misc.dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'erp.views.home', name='home'),
    # url(r'^erp/', include('erp.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^tasks/', include('tasks.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^login/$', 'users.views.login'),
    url(r'^/$', 'users.views.redirectToLogin'),#redirect_to, {'url': '/login/'}),
    url(r'^$', 'users.views.redirectToLogin'),#redirect_to, {'url': '/login/'}),
    url(r'^choose_identity/$', 'users.views.choose_identity'),
    url(r'^logout/$', 'users.views.logout'),
    url(r'^dash/$', 'dash.views.dash_view'),
    url(r'^finance/', include('finance.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^facilities/', include('facilities.urls')),
    url(r'^files_upload/', include('files_upload.urls')),
    url(r'^hospi/',include('hospi.urls')),
    url(r'^barcode/', include('barcode.urls')),
    
    #Password Reset Handling
    url(r'^forgotpassword/reset/$', 'django.contrib.auth.views.password_reset',  {'post_reset_redirect' : '/forgotpassword/reset/done/', 'template_name': 'users/password_reset_form.html', 'email_template_name': 'user/password_email_template.html'}, name="password_reset"),
    url(r'^forgotpassword/reset/done/$', 'django.contrib.auth.views.password_reset_done', {'template_name': 'users/password_reset_done.html'}),
    url(r'^forgotpassword/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',  'django.contrib.auth.views.password_reset_confirm', {'post_reset_redirect' : '/forgotpassword/done/', 'template_name': 'users/password_reset_confirm.html'}),
    url(r'^forgotpassword/done/$', 'django.contrib.auth.views.password_reset_complete', {'template_name': 'users/password_reset_complete.html'}),    
    
    #Password Change
    url(r'^users/changepassword/$',  'django.contrib.auth.views.password_change', {'post_change_redirect' : '/users/changepassword/success/', 'template_name': 'users/password_change_form.html'}),    
    url(r'^users/changepassword/success/$',  'django.contrib.auth.views.password_change_done', {'template_name': 'users/password_change_done.html'}),    
    
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(dajaxice_config.dajaxice_url, include('misc.dajaxice.urls')), # For dajaxice to function corrently
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                 {'document_root': MEDIA_ROOT}),
)

urlpatterns += staticfiles_urlpatterns() # To enable serving static files

facilities/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('facilities.views',
    #Facilities Home
    url(r'^home/$', 'FacilitiesHome'),
    
    #Order Management Views
    url(r'^create/$', 'CreateOrder'), 
    url(r'^approve/(?P<primkey>\d+)/$', 'ApproveOrder'),
    url(r'^delentry/(?P<primkey>\d+)/$', 'DeleteEntry'),
    url(r'^editentry/(?P<primkey>\d+)/$', 'EditEntry'),
    url(r'^delorder/(?P<primkey>\d+)/$', 'DeleteOrder'),
    
    #Add Item to Catalog
    url(r'^addmenuitem/$', 'AddMenuItem'),
    
    #Redirect to Facilites Home
    url(r'^/$', 'FacilitiesRedirect'),
    url(r'^$', 'FacilitiesRedirect'),
                                                                                   
)

facilities/models.py
from django.db import models

from users.models import ERPUser

# Create your models here.

#_________---FACILITY ITEM (An available facility item on the menu)---________
class FacilityItem(models.Model):
    name = models.CharField(max_length=300)
    def __unicode__(self):
        return self.name


class FacilityOrder(models.Model):
    datecreated = models.DateTimeField ('Date Created', auto_now_add = True )
    dateapproved = models.DateTimeField ('Date Approved', blank=True, null=True)
    isapproved = models.BooleanField(default = False)
    items = models.ManyToManyField (FacilityItem, through='ItemEntry')
    creator = models.ForeignKey (ERPUser, related_name='facilityorder_created_set')
    approver = models.ForeignKey (ERPUser, related_name='facilityorder_approved_set', blank=True, null=True)
    


class ItemEntry(models.Model):
    order = models.ForeignKey (FacilityOrder)
    facilityitem = models.ForeignKey (FacilityItem)
    quantity = models.IntegerField(default=0)
    description = models.TextField('Description', blank=True, null=True)
    feedback = models.TextField('Description', blank=True, null=True)
    

facilities/forms.py
from django import forms
from django.forms import ModelForm

#Importing the FacilityItem Model
from facilities.models import FacilityItem

class FacilityItemForm(ModelForm):
    class Meta:
        model = FacilityItem

facilities/views.py
# Create your views here.
# Create your views here.
# Imports
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponseRedirect
import datetime

#Import Add Facility Item form
from facilities.forms import FacilityItemForm

#Import Utilities
from misc.utilities import facilities_check, events_check, facilities_or_events_check

#Importing necessary models
from facilities.models import FacilityOrder, ItemEntry, FacilityItem

#Importing Model Formset Factory
from django.forms.models import modelformset_factory, modelform_factory

#Import Django Exception
from django.core.exceptions import ObjectDoesNotExist



#_______________________---ADD MENU ITEM---_________________________
"""
    Add an item to the catalog
"""
@login_required
@user_passes_test(facilities_check)
def AddMenuItem(request):
    if request.method == 'POST':
        form = FacilityItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('facilities.views.FacilitiesHome')
        else:
            return render_to_response ('facilities/additemtomenu.htm', {'form': form }, context_instance=RequestContext(request))
    else:
        #Display Blank Form
        form = FacilityItemForm()
        context = {'form': form}
        return render_to_response('facilities/additemtomenu.htm', context, context_instance=RequestContext(request))



#___________________________---CREATE ORDER VIEW---___________________________
"""
    PRESENTS AND PROCESSES ORDER FORMSETS
    Presents a formset to a user. This is the user's order. The user then adds entries to his order,
    and submits the form.
"""
@login_required
@user_passes_test(events_check)
def CreateOrder(request):
    #Create a formset for various entries in the creator's order.
    OrderFormset = modelformset_factory(ItemEntry, fields=('facilityitem', 'quantity', 'description'), max_num=1, extra=1)
    
    #For a POST request: Process the data/Add a new row.
    #Code to add a row
    if request.method=='POST':
        if 'add' in request.POST:
            postdata = request.POST.copy()
            postdata['ord-TOTAL_FORMS'] = int(postdata['ord-TOTAL_FORMS']) + 1
            formset = OrderFormset(postdata, prefix='ord')
            showerrors = False
            return render_to_response('facilities/createorder.htm', {'formset': formset, 'showerrors': showerrors}, context_instance=RequestContext(request))
        if 'remove' in request.POST:
            postdata = request.POST.copy()
            postdata['ord-TOTAL_FORMS'] = int(postdata['ord-TOTAL_FORMS']) - 1
            formset = OrderFormset(postdata, prefix='ord')
            showerrors = False
            return render_to_response('facilities/createorder.htm', {'formset': formset, 'showerrors': showerrors}, context_instance=RequestContext(request))
        #Code to process data
        elif 'submit' in request.POST:
            formset = OrderFormset(request.POST, request.FILES, queryset=ItemEntry.objects.none(), prefix = 'ord')
            if formset.is_valid() and formset.has_changed():
                #If the user has entered data, and if it's valid then:
                
                #Register a new order
                neworder = FacilityOrder(creator=request.user.get_profile())
                neworder.save()
                
                #Individually process entries in the order
                entries = formset.save(commit=False)
                
                for itementryinstance in entries:
                    """
                        Note:
                        Adding separate entries for identical facility items is ALLOWED currently.
                        This is because the separate entries might be listed for different purposes,
                        which can be elaborated on using the Description Field.
                    """
                    itementryinstance.order = neworder
                    itementryinstance.save()
                
                return redirect('facilities.views.FacilitiesHome')
            else:
                #Return the form with its errors.
                showerrors = True
                return render_to_response('facilities/createorder.htm', {'formset': formset, 'showerrors': showerrors}, context_instance=RequestContext(request))
    
    else:
        formset = OrderFormset(queryset=ItemEntry.objects.none(), prefix='ord')
        return render_to_response('facilities/createorder.htm', {'formset': formset}, context_instance=RequestContext(request))



#______________________---FACILITIES HOME---_____________________
@login_required
@user_passes_test(facilities_or_events_check)
def FacilitiesHome(request):
    userprofile = request.user.get_profile()

    #Passing a context of information to the template
    context = {}
    
    #Userprofile
    context["userprofile"] = userprofile
    
    context["isapprover"] = facilities_check(request.user)
    
    #Facility Items:
    context["facilityitems"] = FacilityItem.objects.all()
    
    #Pending & approved orders:
    if facilities_check(request.user):
        context["pending"] = FacilityOrder.objects.filter(isapproved=False)
        context["approved"] = FacilityOrder.objects.filter(isapproved=True)
    else:
        context["pending"] = userprofile.facilityorder_created_set.filter(isapproved=False)
        context["approved"] = userprofile.facilityorder_created_set.filter(isapproved=True)    
    
    return render_to_response('facilities/ordersummary.htm', context, context_instance=RequestContext(request))



#______________________---CLEAR AN ORDER---_____________________
"""
Can be done by anybody in Facilities
"""
@login_required
@user_passes_test(facilities_check)
def ApproveOrder(request, primkey):
    try:
        approvedorder = FacilityOrder.objects.get(pk=primkey)
        approvedorder.isapproved = True
        approvedorder.dateapproved = datetime.datetime.now()
        approvedorder.approver = request.user.get_profile()
        approvedorder.save()
        return redirect('facilities.views.FacilitiesHome')
    except ObjectDoesNotExist:
        return redirect('facilities.views.FacilitiesHome')
        
        
#______________________---EDIT AN ENTRY---_____________________
"""
If the user is in Events:
    Can edit only before approval
    
If the user is in facilities:
    Can edit ONLY the FEEDBACK BOX.
"""
@login_required
@user_passes_test(facilities_or_events_check)
def EditEntry(request, primkey):
    #Create a form depending on the department
    if events_check(request.user):
        ItemEntryForm = modelform_factory(ItemEntry, fields=('quantity', 'description'))
    elif facilities_check(request.user):
        ItemEntryForm = modelform_factory(ItemEntry, fields=('feedback', ))
    
    try:
        entry = ItemEntry.objects.get(pk=primkey)
    except:
        return redirect('facilities.views.FacilitiesHome')
    
    if entry.order.isapproved == True:
        return redirect('facilities.views.FacilitiesHome')
    else:
        if request.method == 'POST':
            form= ItemEntryForm(request.POST, instance=entry)
            if form.is_valid():
                form.save()
                return redirect('facilities.views.FacilitiesHome')
            else:
                return render_to_response ('facilities/editentry.htm', {'form': form }, context_instance=RequestContext(request))
        else:
            form=ItemEntryForm(instance=entry)
            return render_to_response ('facilities/editentry.htm', {'form': form }, context_instance=RequestContext(request))
            
            
#______________________---DELETE AN ENTRY---_____________________
"""
Allowed only if:
    1. The user is in Events
    2. The order has not been approved
"""
@login_required
@user_passes_test(events_check)
def DeleteEntry(request, primkey):
    try:
        entry = ItemEntry.objects.get(pk=primkey)
    except:
        return redirect('facilities.views.FacilitiesHome')
    
    if entry.order.isapproved == True:
        return redirect('facilities.views.FacilitiesHome')
    else:
        entry.delete()
        return redirect('facilities.views.FacilitiesHome')
        
        
        
#______________________---DELETE AN ORDER---_____________________
"""
Allowed only if:
    1. The user is in Events
    2. The order has not been approved
"""
@login_required
@user_passes_test(events_check)
def DeleteOrder(request, primkey):
    try:
        order = FacilityOrder.objects.get(pk=primkey)
    except:
        return redirect('facilities.views.FacilitiesHome')
    
    if order.isapproved == True:
        return redirect('facilities.views.FacilitiesHome')
    else:
        order.delete()
        return redirect('facilities.views.FacilitiesHome')
        

        
        
#______________________---Redirector---_____________________
@login_required
@user_passes_test(facilities_or_events_check)
def FacilitiesRedirect(request):
    return redirect('facilities.views.FacilitiesHome')

templates/facilities/additemtomenu.htm
{% extends "base.html" %}

{% load staticfiles %}

{% block extrastyle %}
    <link href="{% static 'dash/coord/coord.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'dash/sidenav.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'dash/table_style.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'dash/datatables/TableTools.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'dash/datatables/TableTools_JUI.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/jui_themes/smoothness/jquery-ui-1.10.3.custom.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'dash/content.css' %}" rel="stylesheet" media="screen">
{% endblock %}

{% block extrascripts %}
    <script src="{% static 'js/jquery-ui-1.10.3.custom.js' %}"></script>
    <script src="{% static 'dash/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'dash/datatables/TableTools.js' %}"></script>
    <script src="{% static 'dash/datatables/ZeroClipboard.js' %}"></script>
    <script src="{% static 'dash/content.js' %}"></script>
    <script src="{% static 'dash/coord/coord.js' %}"></script>
    <!-- <script src="{% static 'dash/dataTables.bootstrap.js' %}"></script> 
        JQuery UI looks better than bootstrap version-->
{% endblock %}
	
{% block content %}
<div class="row-fluid"> 
    <center>
    <div class="span3 sidebar" id="id_content_left">
        <!-- Left content holds the sidebar-nav -->
        <ul class="nav nav-tabs nav-stacked sidenav affix-top">
          <li class="active">
              <a href="{% url facilities.views.AddMenuItem %}"><i class="icon-chevron-right"></i>Add Items</a>
          </li>
          <li>
              <a href="{% url facilities.views.FacilitiesHome %}"><i class="icon-chevron-right"></i>Facilities</a>
          </li>
          <li>
            <a href="{% url dash.views.dash_view %}"><i class="icon-chevron-right"></i> Dashboard </a>
          </li>
        </ul>
    </div>

    <div class="span9" id="id_content_right">
		<h2>Add Facility Items to the Catalog:</h2>
		<br>
		<form action="" method="post" style="position:absolute; right:30%;">
		{% csrf_token %}

		{% if form.errors %}
			<div class="alert alert-error" style="height:15%; width:130%; padding:2%; position:relative; right:30%;">
				<button type='button' class='close' onclick='javascript:this.parentNode.className="alert hide";this.innerHTML="";' style="position:relative; right:2%;">&times;</button>
				<strong>ERROR!</strong><br>
				Error in form: Please fill all fields.
			</div>
			<br>
		{% endif %}
		<table style="width:100%;">
			{{ form.as_table }}
		</table>
		<center><input type="submit" class="btn btn-info" /></center>
		</form>
	</div>

	</center>
	<script type="text/javascript">
		$(".errorlist").hide()
	</script>
</div>
{% endblock %} 

templates/facilities/createorder.htm
{% extends "base.html" %}

{% load staticfiles %}

{% block extrastyle %}
    <link href="{% static 'dash/coord/coord.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'dash/sidenav.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'dash/table_style.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'dash/datatables/TableTools.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'dash/datatables/TableTools_JUI.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/jui_themes/smoothness/jquery-ui-1.10.3.custom.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'dash/content.css' %}" rel="stylesheet" media="screen">
{% endblock %}

{% block extrascripts %}
    <script src="{% static 'js/jquery-ui-1.10.3.custom.js' %}"></script>
    <script src="{% static 'dash/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'dash/datatables/TableTools.js' %}"></script>
    <script src="{% static 'dash/datatables/ZeroClipboard.js' %}"></script>
    <script src="{% static 'dash/content.js' %}"></script>
    <script src="{% static 'dash/coord/coord.js' %}"></script>
    <!-- <script src="{% static 'dash/dataTables.bootstrap.js' %}"></script> 
        JQuery UI looks better than bootstrap version-->
{% endblock %}

{% block content %}
<div class="row-fluid"> 
    <center>
    <div class="span3 sidebar" id="id_content_left">
        <!-- Left content holds the sidebar-nav -->
        <ul class="nav nav-tabs nav-stacked sidenav affix-top">
          <li class="active">
              <a href="{% url facilities.views.CreateOrder %}"><i class="icon-chevron-right"></i>Create Order</a>
          </li>
          <li>
              <a href="{% url facilities.views.FacilitiesHome %}"><i class="icon-chevron-right"></i>Facilities</a>
          </li>
          <li>
            <a href="{% url dash.views.dash_view %}"><i class="icon-chevron-right"></i> Dashboard </a>
          </li>
        </ul>
    </div>

    <div class="span9" id="id_content_right">
        <h1>Create an Order</h1>
        <h3>Select the facility items you want, their description and their quantity.</h3>
        <form method="post" action="">
            {% csrf_token %}
            {{ formset.management_form }}

            <table class="table table-bordered table-hover table-striped" id="table_createOrder" style="width:90%">
                <thead>
                <tr>
                    <th>Select Item</th>
                    <th>Enter Quantity</th>
                    <th>Description</th>
                    <th>Errors</th>
                </tr>
                </thead>
                <tbody>
                {% for form in formset %}
                    {{ form.id }}
                    
                        <tr>
                            <td>{{ form.facilityitem }}</td>
                            <td>{{ form.quantity }}</td>
                            <td>{{ form.description }}</td>
                            <td>
                                {% if showerrors %}
                                    {{ form.non_field_errors }} {{ form.facilityitem.errors }} {{ form.quantity.errors }}
                                {% endif %}
                            </td>
                        </tr>
                    
                {% endfor %}
            </tbody>
            </table>
             <br>
             <input title='Submit this form' type='submit' name='submit' value='Submit' class="btn btn-info" />
             <input title='Add entry' type='submit' name='add' value='Add' class="btn btn-info" />
             <input title='Remove entry' type='submit' name='remove' value='Remove' class="btn btn-info" />
        </form>
    </div>

    </center>
</div>
{% endblock content %}

templates/facilities/ordersummary.htm
{% extends "base.html" %}

{% load staticfiles %}

{% block extrastyle %}
    <link href="{% static 'dash/coord/coord.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'dash/sidenav.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'dash/table_style.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'dash/datatables/TableTools.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'dash/datatables/TableTools_JUI.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/jui_themes/smoothness/jquery-ui-1.10.3.custom.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'dash/content.css' %}" rel="stylesheet" media="screen">
{% endblock %}

{% block extrascripts %}
    <script src="{% static 'js/jquery-ui-1.10.3.custom.js' %}"></script>
    <script src="{% static 'dash/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'dash/datatables/TableTools.js' %}"></script>
    <script src="{% static 'dash/datatables/ZeroClipboard.js' %}"></script>
    <script src="{% static 'dash/content.js' %}"></script>
    <script src="{% static 'dash/coord/coord.js' %}"></script>
    <!-- <script src="{% static 'dash/dataTables.bootstrap.js' %}"></script> 
        JQuery UI looks better than bootstrap version-->
{% endblock %}

{% block content %}

<div class="row-fluid"> 
    <center>
    <div class="span3 sidebar" id="id_content_left">
        <!-- Left content holds the sidebar-nav -->
        <ul class="nav nav-tabs nav-stacked sidenav affix-top">
          <li class="active">
              <a href="{% url facilities.views.FacilitiesHome %}"><i class="icon-chevron-right"></i>Facilities</a>
          </li>
          <li>
            <a href="{% url dash.views.dash_view %}"><i class="icon-chevron-right"></i> Dashboard </a>
          </li>
        </ul>
    </div>

    <div class="span9" id="id_content_right">
        <h2>{% if isapprover %}Approval{% else %}Coordinator{% endif %} Portal</h2>

        <div class="well" style="width:87%; padding:5%">
            <div class="well" style="background:#fff;">
            <h3>Facility Catalog:</h3>
            <table style="font-size:20px; width:auto;" class="table table-bordered table-hover">
                {% if facilityitems %}
                        {% for item in facilityitems %}
                            {% if forloop.counter0|divisibleby:"3" %}
                                {% if forloop.first %}<tr>{% else %}</tr> <tr>{% endif %}
                            {% endif %}
                                    <td><center> {{ item.name }} </center></td>
                            {% if forloop.last %}
                                </tr>
                            {% endif %}
                        {% endfor %}
                {% else %}
                    <p class="text-warning">Catalog Empty</p>
                {% endif %}
                
            {% if isapprover %}
                <tr><td colspan="3"><h4><center> <a href="{% url facilities.views.AddMenuItem %}">Add Facility Item to Catalog</a> </center></h4></td></tr>
            {% else %}
                <tr><th colspan="3"><h4><center> <a href="{% url facilities.views.CreateOrder %}">Place an Order</a> </center></h4></th></tr>
            {% endif %}
            </table>
            </div>
        </div>


        <div class="well" style="width:87%; padding:5%">
            <div class="well" style="background:#fff;">
            <h3>{% if isapprover %}All{% else %}Your{% endif %} Pending Orders:</h3>

            {% if pending %}
                <table class="table table-bordered table-hover" style="width:95%">
                {% for order in pending %}
                        <thead>
                            <td colspan="{% if isapprover %}5{% else %}6{% endif %}">
                                <center>
                                    <p class="pull-left"><b> {{forloop.counter}}. </b></p>
                                    <b>{{ order.creator.user }} - {{ order.datecreated }}</b>
                                </center>
                            </td>
                        </thead>
                        
                        <tbody>
                        <tr> 
                            <td colspan="6">
                                <center>
                                    {% if isapprover %}
                                        <a href="{% url facilities.views.ApproveOrder primkey=order.pk %}">Approve Order</a>
                                    {% endif %}
                                    {% if not isapprover %}
                                        <a href="{% url facilities.views.DeleteOrder primkey=order.pk %}">Delete Order</a>
                                    {% endif %}
                                </center>
                            </td> 
                        </tr>
                        
                        {% for entry in order.itementry_set.all %}
                            <tr>
                                <td>{{entry.facilityitem.name}}</td>
                                <td>{{entry.quantity}}</td>
                                <td>{{entry.description}}</td>
                                <td>{{entry.feedback}}</td>
                                <td><a href="{% url facilities.views.EditEntry primkey=entry.pk %}">{% if isapprover %}Give Feedback{% else %}Edit Entry{% endif %}</a></td>
                                {% if not isapprover %}<td><a href="{% url facilities.views.DeleteEntry primkey=entry.pk %}">Delete Entry</a></td>{% endif %}
                            </tr>
                        {% endfor %}
                        </tbody>
                {% endfor %}
                </table><br />
            {% else %}
                <p class="text-warning">No Pending Orders</p>
            {% endif %}
            </div>
        </div>


        <div class="well" style="width:87%; padding:5%">
            <div class="well" style="background:#fff;">
            <h3>{% if isapprover %}All{% else %}Your{% endif %} Approved Orders:</h3>

            {% if approved %}
                <table class="table table-bordered table-hover" style="width:95%">
                {% for order in approved %}
                        <thead>
                            <td colspan="4">
                                <center>
                                    <p class="pull-left"><b> {{forloop.counter}}. </b></p>
                                    <b>{{ order.creator.user }} - {{ order.datecreated }}</b>
                                </center>
                            </td>
                        </thead>
                        <tr>
                            <td colspan="4">
                                <center>
                                    <b>Approved by {{ order.approver.user }} on {{ order.dateapproved }}</b>
                                </center>
                            </td>
                        </tr>
                        {% for entry in order.itementry_set.all %}
                        <tr>
                            <td>{{entry.facilityitem.name}}</td>
                            <td>{{entry.quantity}}</td>
                            <td>{{entry.description}}</td>
                            <td>{{entry.feedback}}</td>
                        </tr>
                        {% endfor %}
                {% endfor %}
                </table>
            {% else %}
                <p class="text-warning">No Approved Orders</p>
            {% endif %}
            </div>
        </div>

    </div>
    </center>
</div>



{% endblock content %}